
// import { Inter } from '@next/font/google'
// import '../styles/Home.module.css'

//const inter = Inter({ subsets: ['latin'] })

import React , {useState} from 'react';
interface ITableData 
  {
    kjoretoyId:{kjennemerke:string, understellsnummer:string}, 
    kodeBeskrivelse:string, 
    merke:[{merke:string}],
    handelsbetegnelse:string,
    kontrollfrist:string,
    sistGodkjent:string,
    registrertForstegangNorgeDato:string,
  }

function App() {
   const [number , setNumber] = useState("");
   const [tableData , setTableData] = useState({} as ITableData);

   const {kjoretoyId , merke, handelsbetegnelse, kontrollfrist, sistGodkjent, registrertForstegangNorgeDato} = tableData;
  const getVehivleInfo = (number:any) => {
    fetch(
      `/api/info/${number}`,     
    )
      .then((res) => res.json())
      .then((data) => {
        setTableData(data);
        console.log(tableData);
      })
      .catch((err) => console.log(err));
    }

const handleChange = (e:any) => {
  setNumber(e.target.value);
}

  return (
    <div className="App">
      <div >
        <h2>Enter the vehicle registration number</h2>
        <div className='inputDiv'>
          <input type="text" value={number} onChange={handleChange} />
          <button onClick={()=>{
            getVehivleInfo(number);
          }}>Submit</button>
      </div>
      {tableData.kjoretoyId &&
      <table>
        <tr>
          <th>Kjennemerke</th>
          <td>{kjoretoyId?.kjennemerke}</td>
        </tr>
        <tr>
          <th>Understellsnummer</th>
          <td>{kjoretoyId.understellsnummer}</td>
        </tr>
        <tr>
          <th>Merke</th>
          <td>{merke[0].merke}</td>
        </tr>
        <tr>
          <th>Handelsbetegnelse</th>
          <td>{handelsbetegnelse}</td>
        </tr>
        <tr>
          <th>Forstegangsregistrering</th>
          <td>{registrertForstegangNorgeDato}</td>
        </tr>
        <tr>
          <th>SistGodkjent</th>
          <td>{sistGodkjent}</td>
        </tr>
        <tr>
          <th>Kontrollfrist</th>
          <td>{kontrollfrist}</td>
        </tr>
      </table>}
      </div>
    </div>
  );
}

export default App;




// export default function Home() {
//   return (
//     <>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <main className={styles.main}>
//         <div className={styles.description}>
//           <p>
//             Get started by editing&nbsp;
//             <code className={styles.code}>pages/index.tsx</code>
//           </p>
//           <div>
//             <a
//               href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//               target="_blank"
//               rel="noopener noreferrer"
//             >
//               By{' '}
//               <Image
//                 src="/vercel.svg"
//                 alt="Vercel Logo"
//                 className={styles.vercelLogo}
//                 width={100}
//                 height={24}
//                 priority
//               />
//             </a>
//           </div>
//         </div>

//         <div className={styles.center}>
//           <Image
//             className={styles.logo}
//             src="/next.svg"
//             alt="Next.js Logo"
//             width={180}
//             height={37}
//             priority
//           />
//           <div className={styles.thirteen}>
//             <Image
//               src="/thirteen.svg"
//               alt="13"
//               width={40}
//               height={31}
//               priority
//             />
//           </div>
//         </div>

//         <div className={styles.grid}>
//           <a
//             href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Docs <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Find in-depth information about Next.js features and&nbsp;API.
//             </p>
//           </a>

//           <a
//             href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Learn <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Learn about Next.js in an interactive course with&nbsp;quizzes!
//             </p>
//           </a>

//           <a
//             href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Templates <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Discover and deploy boilerplate example Next.js&nbsp;projects.
//             </p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Deploy <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Instantly deploy your Next.js site to a shareable URL
//               with&nbsp;Vercel.
//             </p>
//           </a>
//         </div>
//       </main>
//     </>
//   )
// }
